require("user.options")
require("user.functions_and_filetypes")
require("user.keymaps")
require("user.plugins")
require("user.colorscheme")
require("user.misc")
require("user.cmp")
require("user.lsp")
require("user.telescope")
require("user.treesitter")
require("user.autopairs")
require("user.git")
require("user.nvim-tree")
require("user.bufferline")
require("user.lualine")
require("user.toggleterm")
-- require("user.alpha")
-- require("user.project")
require("user.tmux")
require("user.dap")
